### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by hueniverse** [hapijs/crumb#104]
This module is not maintained to hapi.js standards. Need someone to review issues and PRs and close/resolve them.

**Comment by jonathansamines** [comment]
@hueniverse I would like to help maintaining this module. Will start reviewing existing PR, but I think I need special permissions in order to close issues.

**Comment by hueniverse** [comment]
@jonathansamines Great. Start by making a hapi v17 migration PR and if that goes well we can add the needed permissions.

@stongo I assume you don't want to maintain this anymore.

**Comment by jonathansamines** [comment]
@hueniverse Sure, already working on it. Will come back once I finish the migration.

**Comment by geek** [comment]
@jonathansamines you now have publish permissions on npm for crumb and are also a member of the community group on github.

Thanks for helping out.

**Comment by hueniverse** [comment]
@jonathansamines you haven't been active since requesting to take on this module. There are open issues and PR waiting to be resolved. Still interested in leading the module or should we look for someone else?

**Comment by spanditcaa** [comment]
I would be happy to pick this up @hueniverse.

**Comment by hueniverse** [comment]
@spanditcaa Done. Thanks!
