### ISSUE TITLE
Getting plugin.register.regiter cannot read property of undefined

### ISSUE THREAD

**Issue by popkutty** [hapijs/crumb#110]
HAPI version: ^16.6.2
Crumb version: 6.0.3

Server code:
```

const plugin= [
require('inert'),
{ 
  plugin: require('crumb'),
  options: {
    restful: true
  }
}
]

server.register(plugins, (err) => {

});

```

> if (plugin.register.register) {                             // Required plugin
>                            ^TypeError: Cannot read property 'register' of undefined

**Comment by jonathansamines** [comment]
@popkutty Sorry for the late response, could you put together a reproduction of this issue?

**Comment by Marsup** [comment]
You likely used hapi@17's documentation. It should be `register: require('crumb')` in your snippet.
