### ISSUE TITLE
example/restful.js

### ISSUE THREAD

**Issue by schwamic** [hapijs/crumb#115]
I tested your example with Postman. Unfortunately I got a 403-forbidden despite X-CSRF token in the header. It's because of two different tokens in crumb:
```
header S5FIlACcOaM7BVgEPM1YxMaHRyGyETHF3jUShHhaVnv
request.plugins.crumb hyUp7IW6Q_J7EWAmSIMH9zaZC5T0t71vvXZeX2TEmwQ
```

**Comment by spanditcaa** [comment]
confirmed

**Comment by MeiyappanKannappa** [comment]
Were you able to fix?
