### ISSUE TITLE
Add “dry run” mode

### ISSUE THREAD

**Issue by AlonMiz** [hapijs/crumb#116]
It would be nice to have a "dry run" capability.
This will allow to deploy the plugin in a running app, while not disconnecting all users at the deployment time. This way, the first deploy will be dry (set tokens, allowing users to get the tokens), and the second deploy will validate the tokens.
Meaning, the dry run mode will skip only the csrf tokens validation, not the creation of the csrf tokens.
The current “skip” function option disables the creation as well as the validation. which doesn't help in this situation.

**Comment by AlonMiz** [comment]
Added this PR :)
https://github.com/hapijs/crumb/pull/117

**Comment by spanditcaa** [comment]
Sorry for the delay @AlonMiz - will check this out by this weekend.

**Comment by spanditcaa** [comment]
This was merged in #117
