### ISSUE TITLE
Publish version 7.2.0 to npm

### ISSUE THREAD

**Issue by AlonMiz** [hapijs/crumb#121]
to include the new `enforce:false` capability

**Comment by spanditcaa** [comment]
@hueniverse I don't have npm publish permissions for this repo.  Can you please set me up?

**Comment by hueniverse** [comment]
@spanditcaa npm account?

**Comment by hueniverse** [comment]
Done.

**Comment by spanditcaa** [comment]
Thanks.  Published 7.2.0 (and 7.2.1) @AlonMiz
