### ISSUE TITLE
isSecure settings are not working

### ISSUE THREAD

**Issue by rgaikar-lilly** [hapijs/crumb#145]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: 12.15.0
* *module version with issue*: 8.0.0
* *last module version without issue*: 
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

```js
      key: 'crumb',
      size: 43,
      autoGenerate: true,
      addToViewContext: true,
      cookieOptions: {
        isSecure: true,
        isHttpOnly: true,
        isSameSite: 'Strict',
        encoding: 'iron',
        clearInvalid: true,
        strictHeader: true,
        path: '/',
        domain: process.env.COOKIE_DOMAIN,
        password: process.env.COOKIE_PASSWORD
      },
      headerName: 'X-CSRF-Token',
      restful: true,
      skip: false,
      enforce: true,
      logUnauthorized: false
```

#### What was the result you got?
I tried setting isSecure as false, but it it still mark it as secure in application cookie on browser

#### What result did you expect?
isSecure flag changes does not reflect on client browser.

**Comment by hueniverse** [comment]
Unfortunately, no community resources were available to help resolve this issue after two weeks, and it is being closed. We close unresolved community issues to keep the issue tracker organized and effective. Please check https://hapi.dev/support for other support options.
