### ISSUE TITLE
Host header cannot include URI scheme

### ISSUE THREAD

**Issue by hueniverse** [hapijs/crumb#34]

**Comment by stongo** [comment]
@hueniverse can I get some more details on this please

**Comment by hueniverse** [comment]
https://tools.ietf.org/html/rfc7230#section-5.4

**Comment by stongo** [comment]
@hueniverse does this satisfy the issue then?

**Comment by hueniverse** [comment]
I think so.

**Comment by stongo** [comment]
Closed by https://github.com/hapijs/crumb/pull/44
