### ISSUE TITLE
The ttl of the crumb cookie

### ISSUE THREAD

**Issue by PavelPolyakov** [hapijs/crumb#39]
Hi,

I'm testing crumb currently and have one question.

1. I've configured crumb in a simple way, so all my POST/PUT etc routes protected by the X-CSRF-Token header.
![image](https://cloud.githubusercontent.com/assets/839290/5507658/993019b6-87ad-11e4-90d4-584f7d308ac2.png)

2. I've tested it against the POST route and got it working.
![image](https://cloud.githubusercontent.com/assets/839290/5507665/a9e796bc-87ad-11e4-8f71-f688c6d47619.png)

BUT, the crumb cookie has still the same value. Could you clarify - how long could I use the same crumb cookie? When would it be regenerated by the server and if there would be such moment sometime? Or it would be valid till I would not close the browser.

Are there any configuration options to impact on the cookie regeneration behaviour?

Regards,

**Comment by stongo** [comment]
Crumbs `cookieOptions` allows you to control the crumb cookie. You can use the options specified here http://hapijs.com/api#serverstatename-options

**Comment by stongo** [comment]
Please re-open if you have any other questions

**Comment by PavelPolyakov** [comment]
Hi @stongo ,

Here is how I tried to add the cookieOptions:
![image](https://cloud.githubusercontent.com/assets/839290/5873487/4db0561c-a2f7-11e4-91b5-86b2ca01d6eb.png)

And here is what I see:
![image](https://cloud.githubusercontent.com/assets/839290/5873488/611c97ba-a2f7-11e4-9425-fad3cd3a4593.png)

Should I do that in a different way?

**Comment by PavelPolyakov** [comment]
Found that it should be like:

~~~javascript
{
					register: require('crumb'),
					options : {
						restful      : true,
						cookieOptions: {
							ttl: 86400000
						}
					}
				}
~~~
