### ISSUE TITLE
Provide more relevant feedback

### ISSUE THREAD

**Issue by matthieusieben** [hapijs/crumb#56]
It would be nice if a message was provided to the `Boom.forbidden`. In big applications, where Boom is used everywhere, it may not be trivial to detect where the error was generated.

**Comment by stongo** [comment]
@matthieusieben this is a touchy issue for a security related module, as giving a detailed forbidden message essentially leaks data to potential attackers

that being said, I could investigate writing a server side log message to make debugging easier

**Comment by matthieusieben** [comment]
Some people argue that "Security through obscurity is not security". In the present case, it is obvious to an attacker that a csrf token has to be provided (crumb sets a cookie...) and as easy to detect that the cookie/header may be missing from the request. It would be also possible to determine that the request was rejected in an early stage of its processing by a statistical analysis of the response time...

Anyways, having a server side log message that displays exactly why the csrf did not pass would be good enough imo (and could also facilitate the detection of attacks). If you choose to do this, make sure that you print a different message when the cookie is missing and than when the one present does not match the token in the headers.

**Comment by stongo** [comment]
Ok adding the server side logging right now with a 'logUnauthorized'  option to trigger it. Also good point on this being handy for monitoring

**Comment by steevhise** [comment]
Did this "logUnauthorized" ever get committed and released? Doesn't look like it, it's not in the docs, and as I'm running Crumb 6.0.3 and get an error when I try including that option in the plugin registration.
It would be useful because I'm suddenly seeing crumb not working any more, possibly due to some issue with latest hapi version.

**Comment by spanditcaa** [comment]
@jonathansamines you'll find #112 and #113 which add this capability in master for hapi 17, and I pushed a 6.x.x branch for those still on hapi 16.

**Comment by geek** [comment]
Fixed by #112
