### ISSUE TITLE
update to hapi 9/10

### ISSUE THREAD

**Issue by stongo** [hapijs/crumb#58]
Update crumb to be compatible with hapi 9, and ideally with hapi 10/node 4.x

**Comment by hueniverse** [comment]
@stongo still got the time to maintain this?

**Comment by stongo** [comment]
@hueniverse trying my best, but admit to not doing a great job lately. consider fire lit under my butt. going to catch up this week

**Comment by stongo** [comment]
https://github.com/hapijs/crumb/pull/63
