### ISSUE TITLE
Typo on Line 52

### ISSUE THREAD

**Issue by 58bits** [hapijs/crumb#65]
https://github.com/hapijs/crumb/blob/master/lib/index.js#L52

`restful: settings.resful,` 
should be..
`restful: settings.restful,`

**Comment by arb** [comment]
Documentation PRs are always welcome :+1:

**Comment by 58bits** [comment]
@arb it's not a documentation typo. it's a code change...

```
var routeDefaults = {
        key: settings.key,
        restful: settings.resful,
        source: 'payload'
    };
```

I'd be glad to submit a PR, but for the letter 't' - it seems like it would be quicker for whomever is maintaining this to make a fast commit. Let me know if you'd really like a PR and I'll do it.

**Comment by 58bits** [comment]
ah - @lloydbenson fixed it :-)

**Comment by lloydbenson** [comment]
I submitted a PR, it isn't actually fixed yet.
