### ISSUE TITLE
ES6 style changes and node v4

### ISSUE THREAD

**Issue by hueniverse** [hapijs/crumb#67]
Apply the latest ES6 hapi style:
- use strict
- `const` and `let` where appropriate (linter will tell you where)
- arrow functions where appropriate (linter will tell you where)
- relevant updates to tests + docs
- updating deps and engine in package.json
- avoid `self` and `+=` / `-=` (not optimized yet for let const)
- change .travis to test 4.0, 4, and 5

**Comment by stongo** [comment]
In 6.0.0 release
