### ISSUE TITLE
Heroku disallows host binding but Crumb requires it

### ISSUE THREAD

**Issue by davemackintosh** [hapijs/crumb#68]
I'm stuck in a situation where I need to deploy to Heroku which disallows the binding of a host name (doesn't bind/mount) but Crumb requires I bind to a host in order to work.

Is there a solution to this type of catch-22?

**Comment by stongo** [comment]
It's currently required for checking for origins with CORS, but this 
will soon be handled by an exposed function from Hapi core 
https://github.com/hapijs/hapi/issues/2936. This should eliminate your 
issue in the next version of Crumb.

**Comment by stongo** [comment]
This is no longer required in 6.0.0

**Comment by davemackintosh** [comment]
Will test on Monday, thanks everyone.
