### ISSUE TITLE
Overriding restful options in route

### ISSUE THREAD

**Issue by Blaugold** [hapijs/crumb#74]
I noticed that overriding the default *restful* option (false), in routes does not work. Overriding only seems to work when *restful* is globaly set to true. I think the problem is a short-circuit evaluation in the if statement when branching to validate either by content or by x-csrf-token header:
`
if (settings.restful === false ||
            (!request.route.settings.plugins._crumb || request.route.settings.plugins._crumb.restful === false)){
`
I thought this behaviour is not quite what you would expect.

**Comment by stongo** [comment]
Thanks for the issue, I'll check it out
