### ISSUE TITLE
No crumb cookie using restful example

### ISSUE THREAD

**Issue by genediazjr** [hapijs/crumb#85]
I have tried running the restful.js example but I get no crumb cookie on the response headers as stated.
```
// a "crumb" cookie gets set with any request when not using views
```
I am able to get the crumb as payload on the response of `/generate` but no cookie.

**Comment by stongo** [comment]
I've updated the example. Also try setting CORS `credentials` to `true` (if using CORS)

**Comment by genediazjr** [comment]
got it. thanks!
