### ISSUE TITLE
Example won't launch: `Server.views is not a function`

### ISSUE THREAD

**Issue by citelao** [hapijs/crumb#97]
Even with dependencies installed properly, I could not launch `server.js` in `examples/` until I added the code in the [Vision README](https://github.com/hapijs/vision):

    server.register(require('vision'), (err) => {
        if (err) {
            console.log("Failed to load vision.");
        }
    });

That fixed it.

**Comment by ryanwilliamquinn** [comment]
You should put a PR in for this, I had the same problem.

**Comment by geek** [comment]
Fixed by #106
